live_config_reload = true
[env]
TERM = "xterm-256color"
#import = []

[window]
decorations = "buttonless"
opacity = 0.96
blur = true
startup_mode = "Maximized"
padding = { x = 12, y = 10 }
dynamic_padding = true
option_as_alt = "Both"

[font]
size = 15.0
builtin_box_drawing = true

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Medium"

[font.bold]
style = "Bold"

[font.italic]
style = "Italic"

[font.bold_italic]
style = "Bold Italic"

# Kanagawa Wave
[colors.primary]
background = "#1F1F28"
foreground = "#DCD7BA"

[colors.normal]
black   = "#090618"
red     = "#C34043"
green   = "#76946A"
yellow  = "#C0A36E"
blue    = "#7E9CD8"
magenta = "#957FB8"
cyan    = "#6A9589"
white   = "#C8C093"

[colors.bright]
black   = "#727169"
red     = "#E82424"
green   = "#98BB6C"
yellow  = "#E6C384"
blue    = "#7FB4CA"
magenta = "#938AA9"
cyan    = "#7AA89F"
white   = "#DCD7BA"

[colors.cursor]
text = "#1F1F28"
cursor = "#C8C093"

[colors.selection]
text = "#DCD7BA"
background = "#2D4F67"

[cursor]
style = "Block"
vi_mode_style = "Underline"
unfocused_hollow = true
blink_interval = 500
blink_timeout = 0
thickness = 0.15

[scrolling]
history = 10000
multiplier = 3

[mouse]
hide_when_typing = true
