live_config_reload = true
[env]
TERM = "xterm-256color"
#import = []

[window]
decorations = "buttonless"
opacity = 0.96
blur = true
startup_mode = "Maximized"
padding = { x = 12, y = 10 }
dynamic_padding = true
option_as_alt = "Both"

[font]
size = 15.0
builtin_box_drawing = true

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Medium"

[font.bold]
style = "Bold"

[font.italic]
style = "Italic"

[font.bold_italic]
style = "Bold Italic"

[colors.primary]
background = "#1e1e2e"
foreground = "#cdd6f4"

[colors.normal]
black   = "#45475a"
red     = "#f38ba8"
green   = "#a6e3a1"
yellow  = "#f9e2af"
blue    = "#89b4fa"
magenta = "#f5c2e7"
cyan    = "#94e2d5"
white   = "#bac2de"

[colors.bright]
black   = "#585b70"
red     = "#f38ba8"
green   = "#a6e3a1"
yellow  = "#f9e2af"
blue    = "#89b4fa"
magenta = "#f5c2e7"
cyan    = "#94e2d5"
white   = "#a6adc8"

[colors.cursor]
text = "#1e1e2e"
cursor = "#f5c2e7"

[colors.selection]
text = "#1e1e2e"
background = "#cdd6f4"

[cursor]
style = "Block"
vi_mode_style = "Underline"
unfocused_hollow = true
blink_interval = 500
blink_timeout = 0
thickness = 0.15

[scrolling]
history = 10000
multiplier = 3

[mouse]
hide_when_typing = true
